/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.interfaz;

import java.text.DecimalFormat;
import java.text.ParseException;
import java.util.List;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author castr
 */ 
public class Momento_Evaluativo_2 extends javax.swing.JFrame {
   
    private final DecimalFormat df = new DecimalFormat("#0.00");
    
    public Momento_Evaluativo_2() {
        initComponents();
        this.setLocationRelativeTo(this);
    }
    
    public double promedioNotas(){
        
        List<JLabel> listaNotas = new ArrayList<>();
        
        listaNotas.add(nota1);
        listaNotas.add(nota2);
        listaNotas.add(nota3);
        listaNotas.add(nota4);
        listaNotas.add(nota5);
        listaNotas.add(nota6);
        listaNotas.add(nota7);
        listaNotas.add(nota8);
        listaNotas.add(nota9);
        listaNotas.add(nota10);
        listaNotas.add(nota11);
        listaNotas.add(nota12);

        double suma = 0.0;
        
        for (JLabel nota : listaNotas) {
            suma += Double.parseDouble(nota.getText());
        }
        
        return suma / listaNotas.size();
    }
    
    public int mayoresPromedio() {
        
        List<JLabel> listaNotas = new ArrayList<>();
        
        listaNotas.add(nota1);
        listaNotas.add(nota2);
        listaNotas.add(nota3);
        listaNotas.add(nota4);
        listaNotas.add(nota5);
        listaNotas.add(nota6);
        listaNotas.add(nota7);
        listaNotas.add(nota8);
        listaNotas.add(nota9);
        listaNotas.add(nota10);
        listaNotas.add(nota11);
        listaNotas.add(nota12);
        
        double promedio = promedioNotas();
        int mayores = 0;
        
        for (JLabel nota : listaNotas) {
            if (Double.parseDouble(nota.getText()) > promedio) {
                mayores++;
            }
        }
        return mayores;
    }
    
    
    public int VerificarEstudiante() {
        
        int estudiante = Integer.parseInt(JOptionPane.showInputDialog("Ingrese el numero del estudiante"));
        
        while (true) {
            
            if (estudiante >= 1 && estudiante <= 12) {
                break;
            } else {
                JOptionPane.showMessageDialog(rootPane, "Ingresa un numero de estudiante valido");
                estudiante = Integer.parseInt(JOptionPane.showInputDialog("Ingrese el numero del estudiante"));
            }   
        }
        return estudiante;
    }
    
    public double VerificarNota() {
        
        double nota = Double.parseDouble(JOptionPane.showInputDialog("Ingrese la nota"));
        
        while (true) {
            if (nota >= 0 && nota <= 5.0) {
                break;
            } else {
                JOptionPane.showMessageDialog(rootPane, "Sistema de notas 1.0 a 5.0, ingresa de nuevo");
                nota = Double.parseDouble(JOptionPane.showInputDialog("Ingrese la nota"));
            }
        }
        return (double) nota;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nota1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nota2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nota3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nota4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        nota5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        nota6 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        nota7 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        nota8 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        nota9 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        nota10 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        nota11 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        nota12 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Funciones"));
        jPanel2.setDoubleBuffered(false);
        jPanel2.setLayout(new java.awt.GridLayout(2, 2, 3, 3));

        jButton1.setText("Promedio");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);

        jButton3.setText("# Mayor al Promedio");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);

        jButton2.setText("Cambiar Nota");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);

        jButton4.setText("Salir");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Notas"));
        jPanel3.setLayout(new java.awt.GridLayout(12, 2, 3, 3));

        jLabel1.setText("Estudiante 1");
        jPanel3.add(jLabel1);

        nota1.setText("1.0");
        jPanel3.add(nota1);

        jLabel3.setText("Estudiante 2");
        jPanel3.add(jLabel3);

        nota2.setText("1.0");
        jPanel3.add(nota2);

        jLabel5.setText("Estudiante 3");
        jPanel3.add(jLabel5);

        nota3.setText("1.0");
        jPanel3.add(nota3);

        jLabel7.setText("Estudiante 4");
        jPanel3.add(jLabel7);

        nota4.setText("1.0");
        jPanel3.add(nota4);

        jLabel9.setText("Estudiante 5");
        jPanel3.add(jLabel9);

        nota5.setText("1.0");
        jPanel3.add(nota5);

        jLabel11.setText("Estudiante 6");
        jPanel3.add(jLabel11);

        nota6.setText("1.0");
        jPanel3.add(nota6);

        jLabel13.setText("Estudiante 7");
        jPanel3.add(jLabel13);

        nota7.setText("1.0");
        jPanel3.add(nota7);

        jLabel15.setText("Estudiante 8");
        jPanel3.add(jLabel15);

        nota8.setText("1.0");
        jPanel3.add(nota8);

        jLabel17.setText("Estudiante 9");
        jPanel3.add(jLabel17);

        nota9.setText("1.0");
        jPanel3.add(nota9);

        jLabel19.setText("Estudiante 10");
        jPanel3.add(jLabel19);

        nota10.setText("1.0");
        jPanel3.add(nota10);

        jLabel21.setText("Estudiante 11");
        jPanel3.add(jLabel21);

        nota11.setText("1.0");
        jPanel3.add(nota11);

        jLabel23.setText("Estudiante 12");
        jPanel3.add(jLabel23);

        nota12.setText("1.0");
        jPanel3.add(nota12);

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel25.setText("CALCULADORA DE NOTAS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jLabel25)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel25)
                .addGap(30, 30, 30)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, ("Promedio : " + df.format(promedioNotas())));
    }//GEN-LAST:event_jButton1ActionPerformed

    @SuppressWarnings("empty-statement")
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
            int estudiante = VerificarEstudiante();
            String nota = Double.toString(VerificarNota()) ;

            switch (estudiante) {
                case 1 -> {
                    nota1.setText(nota);
                }
                case 2 -> {
                    nota2.setText(nota);
                }
                case 3 -> {
                    nota3.setText(nota);
                }
                case 4 -> {
                    nota4.setText(nota);
                }
                case 5 -> {
                    nota5.setText(nota);
                }
                case 6 -> {
                    nota6.setText(nota);
                }
                case 7 -> {
                    nota7.setText(nota);
                }
                case 8 -> {
                    nota8.setText(nota);
                }
                case 9 -> {
                    nota9.setText(nota);
                }
                case 10 -> {
                    nota10.setText(nota);
                }
                case 11 -> {
                    nota11.setText(nota);
                }
                case 12 -> {
                    nota12.setText(nota);
                }
                default -> {
                }
            }
        } catch (NumberFormatException e) {
            ;
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, "Estudiantes con notas mayores al promedio " + "(" + df.format(promedioNotas()) + ") : " + mayoresPromedio());
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Momento_Evaluativo_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Momento_Evaluativo_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Momento_Evaluativo_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Momento_Evaluativo_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
    

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Momento_Evaluativo_2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel nota1;
    private javax.swing.JLabel nota10;
    private javax.swing.JLabel nota11;
    private javax.swing.JLabel nota12;
    private javax.swing.JLabel nota2;
    private javax.swing.JLabel nota3;
    private javax.swing.JLabel nota4;
    private javax.swing.JLabel nota5;
    private javax.swing.JLabel nota6;
    private javax.swing.JLabel nota7;
    private javax.swing.JLabel nota8;
    private javax.swing.JLabel nota9;
    // End of variables declaration//GEN-END:variables
}
